//
// Created by qazzer on 08/11/2019.
//

#ifndef MODERNCPPCONCURENCY_UNIT5_MEMORY_ORDER_CONSUME_H
#define MODERNCPPCONCURENCY_UNIT5_MEMORY_ORDER_CONSUME_H

void unit5_memory_order_consume();


#endif //MODERNCPPCONCURENCY_UNIT5_MEMORY_ORDER_CONSUME_H
