//
// Created by qazzer on 29/10/2019.
//

#ifndef MODERNCPPCONCURENCY_UNIT3_PROMISES_SHARED_FUTURES_H
#define MODERNCPPCONCURENCY_UNIT3_PROMISES_SHARED_FUTURES_H

void unit3_run_promise_code();

#endif //MODERNCPPCONCURENCY_UNIT3_PROMISES_SHARED_FUTURES_H
