//
// Created by qazzer on 04/11/2019.
//

#ifndef MODERNCPPCONCURENCY_UNIT5_MEMORY_ORDERING_H
#define MODERNCPPCONCURENCY_UNIT5_MEMORY_ORDERING_H


void unit5_important_relationships();

#endif //MODERNCPPCONCURENCY_UNIT5_MEMORY_ORDERING_H
