//
// Created by qazzer on 24/10/2019.
//

#ifndef MODERNCPPCONCURENCY_UNIT2_DEADLOCK_UNIQUELOCK_H
#define MODERNCPPCONCURENCY_UNIT2_DEADLOCK_UNIQUELOCK_H


void run_code_deadlock();
void run_uniquelock_code();


#endif //MODERNCPPCONCURENCY_UNIT2_DEADLOCK_UNIQUELOCK_H
