//
// Created by qazzer on 05/11/2019.
//

#ifndef MODERNCPPCONCURENCY_UNIT5_MEMORY_ORDER_RELAXED_H
#define MODERNCPPCONCURENCY_UNIT5_MEMORY_ORDER_RELAXED_H


void unit5_memory_order_relaxed();

#endif //MODERNCPPCONCURENCY_UNIT5_MEMORY_ORDER_RELAXED_H
